# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - master
 paths:
   include:
   - "edge"

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'iot-module-env-vars'
  - name: ProjectPath
    value: "edge/VehicleTelemetryModules"

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      for folder in edge/*Module; do
          echo "$(basename "$folder")"
          dotnet publish -c Release -o out $folder/$folder.csproj
      done

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'
