# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
     - master
 paths:
   include:
   - "edge"

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'iot-module-env-vars'
  - name: ProjectPath
    value: "edge/VehicleTelemetryModules"

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'
      
- task: AzureIoTEdge@2
  inputs:
    action: 'Build module images'
    templateFilePath: '$(ProjectPath)/deployment.template.json'
    defaultPlatform: 'amd64'

- task: AzureIoTEdge@2
  inputs:
    action: 'Push module images'
    containerregistrytype: 'Azure Container Registry'
    azureSubscriptionEndpoint: 'Azure Internal Consumption(ef4a11cd-7f45-41ab-b4a3-02776b287779)'
    azureContainerRegistry: '{"loginServer":"iotmoduleregistry.azurecr.io", "id" : "/subscriptions/ef4a11cd-7f45-41ab-b4a3-02776b287779/resourceGroups/iot-demo-rg/providers/Microsoft.ContainerRegistry/registries/iotmoduleregistry"}'
    templateFilePath: '$(ProjectPath)/deployment.template.json'
    defaultPlatform: 'amd64'
    fillRegistryCredential: 'true'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

